import {worlds,freshSave,restoreSave,unlock,evolve,upgradeCost,upgrade,reward} from './model.js';
import {icon,hydrateIcons} from './icons.js';
import {createRun,moveRun,stepRun} from './runner.js';
import {GameRenderer,loadAssets} from './renderer.js';

const $=id=>document.getElementById(id),canvas=$('scene'),sheet=$('sheet');
function fitInstalledScreen(){if(navigator.standalone!==true)return;const portrait=matchMedia('(orientation: portrait)').matches;const height=portrait?Math.max(screen.width,screen.height):Math.min(screen.width,screen.height);for(const element of [document.documentElement,document.body,$('app')])element.style.height=`${Math.max(innerHeight,height)}px`;}
fitInstalledScreen();window.addEventListener('resize',fitInstalledScreen);window.addEventListener('pageshow',fitInstalledScreen);
const images=['forest','neon','ocean'],symbols=['leaf','bolt','tide'],accents=['#dcf79b','#dcc1f5','#a4e9e4'];
const subtitles=['Follow your wild.','Find your spark.','Go a little deeper.'];
let save,preferences={sound:true,haptics:true,tutorial:false};
try{save=restoreSave(localStorage.getItem('wildstride-v1'));const p=JSON.parse(localStorage.getItem('wildstride-preferences')||'{}');for(const key of Object.keys(preferences))if(typeof p[key]==='boolean')preferences[key]=p[key];}catch{save??=freshSave();}
let previewWorld=save.world,tab='explore',mode='camp',run=null,renderer=null,lastTime=0,countdown=3,beforePause='running',toastTimer,installPrompt=null,audio=null,coinTime=0,activeSheet=null,evolutionTimer;
let hudDistance=-1,hudEnergy=-1,hudHealth=-1,assetsReady=false;
hydrateIcons();
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3400);}
function persist(){try{localStorage.setItem('wildstride-v1',JSON.stringify(save));return true;}catch{toast('Device storage is unavailable. Keep this app open to retain your progress.');return false;}}
function savePreferences(){try{localStorage.setItem('wildstride-preferences',JSON.stringify(preferences));}catch{toast('Settings could not be saved on this device.');}}
function vibrate(pattern=8){if(preferences.haptics&&navigator.vibrate)navigator.vibrate(pattern);}
function unlockAudio(){if(!preferences.sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});}catch{}}
function sound(type){if(!preferences.sound)return;unlockAudio();if(!audio||audio.state!=='running')return;if(type==='coin'&&audio.currentTime-coinTime<.08)return;if(type==='coin')coinTime=audio.currentTime;const notes={coin:[880,1320],hit:[130,90],start:[440,660,880],evolve:[523,659,784,1046]}[type]||[660];notes.forEach((frequency,index)=>{const start=audio.currentTime+index*(type==='evolve'?.13:.055),o=audio.createOscillator(),g=audio.createGain();o.type=type==='hit'?'triangle':'sine';o.frequency.setValueAtTime(frequency,start);o.connect(g);g.connect(audio.destination);g.gain.setValueAtTime(.0001,start);g.gain.exponentialRampToValueAtTime(.055,start+.008);g.gain.exponentialRampToValueAtTime(.0001,start+.19);o.start(start);o.stop(start+.2);o.onended=()=>{o.disconnect();g.disconnect();};});}
function portrait(world,stage,extra=''){return `<span class="creature ${extra}" style="--species:${world};--form:${stage}" role="img" aria-label="${worlds[world].names[stage]}"></span>`;}
function bond(world){const c=save.creatures[world],goal=worlds[world].xp[c.stage],percent=c.stage===2?100:Math.min(100,c.xp/goal*100);return `<div class="bond-label"><span>${c.stage===2?'Final form':'Evolution bond'}</span><span>${c.stage===2?c.xp+' XP':c.xp+' / '+goal+' XP'}</span></div><div class="bond-track" role="progressbar" aria-label="Evolution bond" aria-valuemin="0" aria-valuemax="${goal||Math.max(1,c.xp)}" aria-valuenow="${goal?Math.min(c.xp,goal):c.xp}"><i style="width:${percent}%"></i></div>`;}
function ability(world,stage){return [`Crystals give ${stage+2} energy each.`,`${(1.8+stage*.6).toFixed(1)} seconds of protection after a hit.`,`Start each run with ${stage+1} extra ${stage===0?'heart':'hearts'}.`][world];}
function setTheme(world){document.documentElement.style.setProperty('--accent',accents[world]);document.documentElement.style.setProperty('--world-image',`url('assets/${images[world]}.webp')`);}
function sizeHero(){if(!renderer||mode!=='camp')return;const i=save.unlocked[previewWorld]?save.active:previewWorld,stage=save.creatures[i].stage,region=renderer.frontRegions[i][stage],cell=renderer.assets.creatures.width/3,rect=$('hero-stage').getBoundingClientRect();if(!rect.height)return;$('hero-creature').style.width=Math.min(475,rect.height*.78/(region.h/cell),rect.width*1.33)+'px';$('hero-creature').style.setProperty('--hero-y',-((region.y%cell+region.h/2)/cell*100)+'%');}
new ResizeObserver(sizeHero).observe($('hero-stage'));
function renderCamp(){const w=worlds[previewWorld],available=save.unlocked[previewWorld],active=available?save.active:previewWorld,c=save.creatures[active];setTheme(previewWorld);$('balance').textContent=save.energy.toLocaleString();$('balance').parentElement.setAttribute('aria-label',`${save.energy} energy`);$('world-number').textContent=`WORLD 0${previewWorld+1} · ${['THE BEGINNING','AFTER THE AFTERGLOW','BEYOND THE SHALLOWS'][previewWorld]}`;$('world-title').textContent=w.name;$('world-subtitle').textContent=subtitles[previewWorld];$('hero-creature').style.setProperty('--species',active);$('hero-creature').style.setProperty('--form',c.stage);$('hero-creature').setAttribute('aria-label',worlds[active].names[c.stage]);$('hero-badge').innerHTML=`<span class="tiny-dot"></span> ${!available?'A NEW FRIEND IS WAITING':c.stage<2&&c.xp>=worlds[active].xp[c.stage]?'READY FOR SOMETHING EXTRAORDINARY':save.best?'ONE MORE ADVENTURE':'YOUR ADVENTURE STARTS HERE'}`;$('worlds').innerHTML=worlds.map((x,i)=>`<button class="world-chip ${i===previewWorld?'selected':''}" data-world="${i}" aria-label="${x.name}${save.unlocked[i]?'':', locked'}" aria-pressed="${i===previewWorld}"><span class="chip-symbol">${icon(symbols[i])}${save.unlocked[i]?'':`<span class="lock-marker">${icon('lock')}</span>`}</span><span class="chip-name">${x.element}</span></button>`).join('');
$('active-companion').hidden=!available;$('unlock-copy').hidden=available;if(available){const selected=save.creatures[save.active];$('active-companion').innerHTML=`${portrait(save.active,selected.stage)}<div class="companion-summary"><div class="companion-name-line"><strong>${worlds[save.active].names[selected.stage]}</strong><span class="form-label">FORM 0${selected.stage+1}</span></div>${bond(save.active)}</div><span class="chevron">${icon('chevron-right')}</span>`;$('active-companion').setAttribute('aria-label',`View ${worlds[save.active].names[selected.stage]} and evolution progress`);$('play-label').textContent='LET’S RUN';$('play').disabled=!assetsReady;$('best-line').innerHTML=`${icon('trophy')} BEST ${save.best.toLocaleString()} m <span>·</span> ONE MORE ADVENTURE`;}else{$('unlock-copy').innerHTML=`<strong>A new world. A new friend.</strong><p>Discover ${w.name} and meet ${w.names[0]}.</p>`;$('play-label').textContent=`UNLOCK · ${w.cost} ENERGY`;$('play').disabled=save.energy<w.cost;$('best-line').textContent=save.energy<w.cost?`${w.cost-save.energy} MORE ENERGY TO YOUR NEXT DISCOVERY`:'YOUR NEXT CHAPTER IS READY';}
$('collection').innerHTML=worlds.map((x,i)=>{const creature=save.creatures[i],unlocked=save.unlocked[i],ready=creature.stage<2&&creature.xp>=x.xp[creature.stage];return `<button class="companion-card ${unlocked?'':'locked'}" data-companion="${i}" style="--species-color:${accents[i]}" aria-label="${x.names[creature.stage]}${unlocked?'':', locked'}">${portrait(i,creature.stage)}<div class="card-info"><div class="element-label">${icon(symbols[i])} ${x.element}</div><h2>${x.names[creature.stage]}</h2><p>${unlocked?x.ability:'Discover in '+x.name}</p>${unlocked?ready?`<span class="evolve-indicator">${icon('sparkle')} Ready to evolve</span>`:bond(i):`<span class="card-unlock">${icon('lock')} ${x.cost} energy</span>`}</div>${save.active===i?`<span class="equipped">${icon('check')}</span>`:''}</button>`;}).join('');
$('upgrade-list').innerHTML=[['magnet','Crystal magnet','Wider crystal pickup range','magnet'],['vitality','Wild heart','One extra heart per level','heart']].map(([key,title,description,symbol])=>{const level=save.upgrades[key],cost=upgradeCost(save,key);return `<article class="upgrade-card"><header><span class="upgrade-symbol">${icon(symbol)}</span><div class="upgrade-levels" aria-label="Level ${level} of 3">${[0,1,2].map(i=>`<i class="${i<level?'filled':''}"></i>`).join('')}</div></header><h2>${title}</h2><p>${description}</p><button class="primary" data-upgrade="${key}" ${level===3||save.energy<cost?'disabled':''}>${level===3?'FULLY UPGRADED':`UPGRADE · ${cost} ENERGY`}${icon(level===3?'check':'arrow-right')}</button></article>`;}).join('');sizeHero();}
function changeWorld(index){if(mode!=='camp')return;previewWorld=(index+3)%3;if(save.unlocked[previewWorld]){save.world=previewWorld;persist();}vibrate();renderCamp();}
function selectTab(next){if(mode!=='camp')return;tab=next;for(const id of ['explore','companions','upgrades'])$(id).hidden=id!==tab;$('app').classList.toggle('library-mode',tab!=='explore');document.querySelectorAll('[data-tab]').forEach(button=>{const selected=button.dataset.tab===tab;button.classList.toggle('selected',selected);if(selected)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current');});vibrate();}
$('worlds').onclick=e=>{const button=e.target.closest('[data-world]');if(button)changeWorld(+button.dataset.world);};$('previous-world').onclick=()=>changeWorld(previewWorld-1);$('next-world').onclick=()=>changeWorld(previewWorld+1);document.querySelector('.tab-bar').onclick=e=>{const button=e.target.closest('[data-tab]');if(button)selectTab(button.dataset.tab);};
let heroTouch=null;$('hero-stage').addEventListener('pointerdown',e=>{heroTouch={x:e.clientX,y:e.clientY};});$('hero-stage').addEventListener('pointerup',e=>{if(!heroTouch)return;const dx=e.clientX-heroTouch.x,dy=e.clientY-heroTouch.y;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy))changeWorld(previewWorld+(dx<0?1:-1));heroTouch=null;});$('hero-stage').addEventListener('pointercancel',()=>heroTouch=null);
function showSheet(content,kind){activeSheet=kind;$('sheet-content').innerHTML=content;if(!sheet.open)sheet.showModal();sheet.scrollTop=0;vibrate();}
function sheetHeader(label){return `<div class="sheet-header"><div class="eyebrow">${label}</div><button class="round-button" data-close-sheet aria-label="Close">${icon('close')}</button></div>`;}
function showCompanion(i){const w=worlds[i],c=save.creatures[i],unlocked=save.unlocked[i],ready=c.stage<2&&c.xp>=w.xp[c.stage];const content=`${sheetHeader('COMPANION FIELD GUIDE')}<div class="sheet-hero" style="--accent:${accents[i]}">${portrait(i,c.stage)}</div><div class="sheet-title"><div class="element-label" style="color:${accents[i]}">${icon(symbols[i])} ${w.element}</div><h2>${w.names[c.stage]}</h2><p>${ability(i,c.stage)}</p></div><div class="evolution-chain">${w.names.map((name,stage)=>`${stage?icon('chevron-right'):''}<div class="${stage>c.stage?'future':''}">${portrait(i,stage)}<strong>${name}</strong><small>${stage===0?'FIRST FORM':w.xp[stage-1]+' XP'}</small></div>`).join('')}</div>${unlocked?bond(i):''}<div class="sheet-actions">${unlocked?`${ready?`<button class="primary" data-evolve="${i}">${icon('sparkle')} TIME TO EVOLVE ${icon('arrow-right')}</button>`:''}<button class="${save.active===i?'secondary':'primary'}" data-select="${i}" ${save.active===i?'disabled':''}>${save.active===i?'YOUR ACTIVE COMPANION':'RUN WITH '+w.names[c.stage].toUpperCase()}</button>`:`<button class="primary" data-unlock="${i}" ${save.energy<w.cost?'disabled':''}>UNLOCK · ${w.cost} ENERGY ${icon('lock')}</button><p class="small-note">Includes ${w.name} and ${w.names[0]}.</p>`}</div>`;showSheet(content,'companion');}
$('active-companion').onclick=()=>showCompanion(save.active);$('collection').onclick=e=>{const b=e.target.closest('[data-companion]');if(b)showCompanion(+b.dataset.companion);};
function showTutorial(startAfter=false){showSheet(`${sheetHeader('YOUR FIRST ADVENTURE')}<h2 class="sheet-heading">Trust your<br>instincts.</h2><p class="tutorial-copy">Swipe anywhere while you run.<br>There’s always a clear lane.</p>${[['arrow-right','Find your lane','Swipe left or right to dodge obstacles.'],['arrow-up','A little leap','Swipe up to jump over rocks.'],['arrow-down','Stay low','Swipe down to slide beneath stone gates.'],['gem','Bring the energy','Collect crystals. Every 5 meters earns 1 bond XP.']].map(([symbol,title,description])=>`<div class="instruction"><span class="instruction-icon">${icon(symbol)}</span><div><strong>${title}</strong><p>${description}</p></div></div>`).join('')}<p class="small-note">Arrow keys and on-screen controls work too.<br>Pause anytime to bank your run.</p><button class="primary" data-tutorial-done="${startAfter}">I’M READY ${icon('check')}</button>`,'tutorial');}
function showSettings(){const standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone;showSheet(`${sheetHeader('MAKE YOURSELF AT HOME')}<h2 class="sheet-heading">Your kind of wild.</h2><div class="setting-row"><span>${icon('sound')} Sound effects</span><button class="switch" role="switch" aria-label="Sound effects" aria-checked="${preferences.sound}" data-setting="sound"><i></i></button></div>${'vibrate'in navigator?`<div class="setting-row"><span>${icon('phone')} Haptic feedback</span><button class="switch" role="switch" aria-label="Haptic feedback" aria-checked="${preferences.haptics}" data-setting="haptics"><i></i></button></div>`:''}<button class="settings-button" data-how-to>${icon('compass')} How to play <span class="chevron">${icon('chevron-right')}</span></button><div class="settings-section"><div class="eyebrow">YOUR JOURNEY</div><div class="setting-row"><span>Best distance</span><b>${save.best.toLocaleString()} m</b></div><div class="setting-row"><span>Worlds discovered</span><b>${save.unlocked.filter(Boolean).length} / 3</b></div><div class="setting-row"><span>Creature forms</span><b>${save.creatures.reduce((sum,c,i)=>sum+(save.unlocked[i]?c.stage+1:0),0)} / 9</b></div></div>${standalone?`<div class="install-guide"><strong>Your adventure, anywhere.</strong>Installed on this device. Your progress stays here.</div>`:installPrompt?`<button class="primary" data-install>${icon('download')} ADD TO HOME SCREEN</button>`:`<div class="install-guide"><strong>Make room for the wild.</strong>On iPhone, open in Safari, tap Share, then Add to Home Screen. On Android, use your browser’s Install app option.</div>`}<p class="small-note">${offlineReady?'Ready to play offline.':'Connect once to download the offline game.'}<br>Saved on this device · No accounts, ads, or purchases.<br>Clearing site data removes your progress.</p>`,'settings');}
let offlineReady=false;$('settings').onclick=showSettings;
sheet.addEventListener('click',async e=>{if(e.target===sheet){sheet.close();return;}const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-close-sheet'))sheet.close();if(b.hasAttribute('data-select')){save.active=+b.dataset.select;persist();renderCamp();sheet.close();toast(`${worlds[save.active].names[save.creatures[save.active].stage]} is ready to run.`);}if(b.hasAttribute('data-unlock'))unlockWorld(+b.dataset.unlock);if(b.hasAttribute('data-evolve'))beginEvolution(+b.dataset.evolve);if(b.hasAttribute('data-tutorial-done')){preferences.tutorial=true;savePreferences();sheet.close();if(b.dataset.tutorialDone==='true')startRun();}if(b.hasAttribute('data-how-to'))showTutorial();if(b.hasAttribute('data-setting')){const key=b.dataset.setting;preferences[key]=!preferences[key];savePreferences();b.setAttribute('aria-checked',String(preferences[key]));vibrate();if(key==='sound'&&preferences.sound)sound('coin');}if(b.hasAttribute('data-install')&&installPrompt){try{await installPrompt.prompt();await installPrompt.userChoice;}catch{toast('Use your browser’s Add to Home Screen option.');}installPrompt=null;showSettings();}});
function unlockWorld(i){if(!unlock(save,i))return;save.world=i;save.active=i;previewWorld=i;persist();if(sheet.open)sheet.close();renderCamp();selectTab('explore');sound('evolve');vibrate([12,30,12]);toast(`${worlds[i].name} and ${worlds[i].names[0]} unlocked!`);}
$('upgrade-list').onclick=e=>{const b=e.target.closest('[data-upgrade]');if(b&&upgrade(save,b.dataset.upgrade)){persist();renderCamp();sound('coin');vibrate();toast('A little stronger. Ready for your next run.');}};
$('play').onclick=()=>{unlockAudio();if(!save.unlocked[previewWorld]){unlockWorld(previewWorld);return;}if(!preferences.tutorial){showTutorial(true);return;}startRun();};
function beginEvolution(i){if(!save.unlocked[i]||!evolve(save,i))return;persist();sheet.close();mode='evolution';$('camp').hidden=true;const c=save.creatures[i],w=worlds[i];setTheme(i);$('evolution-screen').hidden=false;$('evolution-screen').innerHTML=`<div class="eyebrow" id="evolution-eyebrow">SOMETHING EXTRAORDINARY…</div><h2 id="evolution-title">Growing together.</h2><div class="evolution-art"><div class="ring"></div><div class="ring"></div><div class="ring"></div>${portrait(i,c.stage-1,'transforming')}</div><h3 id="evolution-name">${w.names[c.stage-1]}</h3><p id="evolution-ability">Every adventure brought you here.</p><button class="primary" id="finish-evolution" disabled>MEET THE NEW YOU ${icon('heart')}</button>`;const delay=matchMedia('(prefers-reduced-motion: reduce)').matches?100:1400;clearTimeout(evolutionTimer);evolutionTimer=setTimeout(()=>{$('evolution-eyebrow').textContent='A NEW CHAPTER BEGINS';$('evolution-title').textContent='Wildly evolved.';$('evolution-name').textContent=w.names[c.stage];$('evolution-ability').textContent=ability(i,c.stage);const creature=$('evolution-screen').querySelector('.creature');creature.style.setProperty('--form',c.stage);creature.setAttribute('aria-label',w.names[c.stage]);creature.classList.remove('transforming');$('finish-evolution').disabled=false;$('finish-evolution').focus();sound('evolve');vibrate([12,40,20]);},delay);$('finish-evolution').onclick=()=>{mode='camp';$('evolution-screen').hidden=true;$('camp').hidden=false;renderCamp();};}
function startRun(){if(!assetsReady)return;run=createRun(save);mode='countdown';countdown=3;hudDistance=hudEnergy=hudHealth=-1;$('camp').hidden=true;$('game-screen').hidden=false;$('run-overlay').hidden=true;$('countdown').hidden=false;$('countdown-number').textContent='3';$('run-controls').hidden=false;$('run-controls').inert=false;document.querySelector('.run-hud').inert=false;$('run-world').textContent=worlds[save.world].name.toUpperCase();renderer.resize();renderer.particles=[];renderer.shake=0;updateHUD();canvas.focus();sound('start');vibrate();}
function updateHUD(){const distance=Math.floor(run.distance);if(distance!==hudDistance){$('distance').textContent=distance.toLocaleString();hudDistance=distance;}if(run.energy!==hudEnergy){$('run-energy').textContent=run.energy;hudEnergy=run.energy;}if(run.health!==hudHealth){$('health').innerHTML=Array.from({length:run.maxHealth},(_,i)=>`<span class="${i<run.health?'':'empty'}">${icon('heart')}</span>`).join('');$('health').setAttribute('aria-label',`${run.health} hearts remaining`);hudHealth=run.health;}}
function pauseRun(){if(!['running','countdown'].includes(mode))return;beforePause=mode;mode='paused';$('countdown').hidden=true;$('run-controls').inert=true;document.querySelector('.run-hud').inert=true;$('run-overlay').hidden=false;$('run-overlay').innerHTML=`<div class="overlay-content"><span class="big-icon">${icon('moon')}</span><div class="eyebrow">TAKE A BREATHER</div><h2>The wild<br>can wait.</h2><p>Your companion isn’t going anywhere.</p><button class="primary" data-resume>KEEP RUNNING ${icon('play')}</button><button class="secondary" ${beforePause==='countdown'?'data-camp':'data-end'}>${beforePause==='countdown'?'Back to camp':'End run & collect'}</button></div>`;$('run-overlay').querySelector('[data-resume]').focus();}
function resumeRun(){if(mode!=='paused')return;mode=beforePause;$('run-overlay').hidden=true;$('countdown').hidden=mode!=='countdown';$('run-controls').inert=false;document.querySelector('.run-hud').inert=false;canvas.focus();unlockAudio();}
function finishRun(){if(!run||run.banked)return;run.banked=true;run.ended=true;const best=run.distance>save.best,xp=reward(save,run.active,run.distance,run.energy);persist();mode='results';updateHUD();renderCamp();$('run-controls').hidden=true;$('run-controls').inert=true;document.querySelector('.run-hud').inert=true;$('countdown').hidden=true;$('run-overlay').hidden=false;const c=save.creatures[run.active],ready=c.stage<2&&c.xp>=worlds[run.active].xp[c.stage];$('run-overlay').innerHTML=`<div class="overlay-content"><div class="eyebrow">${best?'A NEW PERSONAL BEST':'EVERY ADVENTURE COUNTS'}</div><h2>Wild run.<br>Well earned.</h2>${portrait(run.active,run.stage,'result-creature')}<div class="result-stats"><div>${icon('flag')}<strong>${Math.floor(run.distance).toLocaleString()}</strong><small>meters explored</small></div><div>${icon('gem')}<strong>+${run.energy}</strong><small>energy banked</small></div><div>${icon('heart')}<strong>+${xp}</strong><small>bond XP</small></div></div>${ready?'<div class="reward-note">Your companion is ready to evolve at camp.</div>':''}<button class="primary" data-retry>ONE MORE RUN ${icon('refresh')}</button><button class="secondary" data-camp>Back to camp</button></div>`;$('run-overlay').querySelector('[data-retry]').focus();if(best)sound('evolve');}
function returnCamp(){mode='camp';run=null;$('game-screen').hidden=true;$('camp').hidden=false;renderCamp();$('play').focus();}
$('pause').onclick=pauseRun;$('run-overlay').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-resume'))resumeRun();if(b.hasAttribute('data-end'))finishRun();if(b.hasAttribute('data-camp'))returnCamp();if(b.hasAttribute('data-retry'))startRun();};
function act(action){if(mode!=='running')return;moveRun(run,action);vibrate(5);}
$('run-controls').addEventListener('pointerdown',e=>{const b=e.target.closest('[data-action]');if(b){e.preventDefault();act(b.dataset.action);}});$('run-controls').addEventListener('click',e=>{if(e.detail===0){const b=e.target.closest('[data-action]');if(b)act(b.dataset.action);}});
let touch=null;canvas.addEventListener('pointerdown',e=>{touch={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointerup',e=>{if(!touch)return;const dx=e.clientX-touch.x,dy=e.clientY-touch.y;if(Math.max(Math.abs(dx),Math.abs(dy))>20)act(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'slide':'jump');else act('jump');touch=null;});canvas.addEventListener('pointercancel',()=>touch=null);
window.addEventListener('keydown',e=>{if(sheet.open)return;const action={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'jump',w:'jump',' ':'jump',ArrowDown:'slide',s:'slide'}[e.key];if(e.target.tagName==='BUTTON'&&(e.key===' '||e.key==='Enter'))return;if(action&&mode==='running'){e.preventDefault();act(action);}if(e.key==='Escape'||e.key==='p'){if(mode==='paused')resumeRun();else pauseRun();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseRun();});window.addEventListener('blur',pauseRun);window.addEventListener('pagehide',pauseRun);
function frame(time){const dt=Math.min((time-lastTime)/1000,.05);lastTime=time;if(mode==='countdown'){countdown-=dt;$('countdown-number').textContent=Math.max(1,Math.ceil(countdown));if(countdown<=0){mode='running';$('countdown').hidden=true;sound('start');}}if(mode==='running'){for(const event of stepRun(run,dt)){renderer.emit(event);if(event.type==='crystal')sound('coin');if(event.type==='hit'){sound('hit');vibrate([25,20,25]);$('hit-flash').classList.remove('active');void $('hit-flash').offsetWidth;$('hit-flash').classList.add('active');}if(event.type==='ended')finishRun();}updateHUD();}if(renderer&&run&&['running','countdown','paused'].includes(mode))renderer.draw(run,time/1000,dt,mode==='running');requestAnimationFrame(frame);}
async function boot(){try{$('loading-bar').style.width='0%';const assets=await loadAssets(progress=>$('loading-bar').style.width=`${progress*100}%`);renderer=new GameRenderer(canvas,assets);assetsReady=true;renderCamp();$('loading-screen').classList.add('done');setTimeout(()=>$('loading-screen').hidden=true,450);}catch(error){$('loading-screen').innerHTML=`${icon('sparkle')}<h2>Almost there.</h2><p>${error.message}</p><button class="primary" id="retry-load" style="width:180px;margin-top:20px">TRY AGAIN</button>`;$('retry-load').onclick=()=>location.reload();}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;if(sheet.open&&activeSheet==='settings')showSettings();});window.addEventListener('appinstalled',()=>toast('Installed. Your next adventure is a tap away.'));
if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>{offlineReady=true;}).catch(()=>{offlineReady=false;});let refreshing=false;const hadController=!!navigator.serviceWorker.controller;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(hadController&&!refreshing&&mode==='camp'&&!sheet.open){refreshing=true;location.reload();}});}
renderCamp();boot();requestAnimationFrame(frame);
