export const worlds=[
 {name:'Verdant Ruins',label:'THE OVERGROWN SANCTUARY',intro:'Into the<br>evergreen.',copy:'Ancient paths. New beginnings.<br>There’s something wild in you.',icon:'❋',cost:0,colors:['#73978b','#264c45','#142e2e','#c4bd88'],element:'LEAF',names:['Mossling','Fernhorn','Sylvanox'],color:'#b6d87e',ability:'Energy affinity',description:'Earn more energy from every crystal.',xp:[120,350]},
 {name:'Neon District',label:'THE CITY THAT NEVER SLEEPS',intro:'Chase the<br>afterglow.',copy:'Electric streets. Infinite horizons.<br>Find your spark in the city.',icon:'ϟ',cost:100,colors:['#514b78','#292c51','#141b32','#64618c'],element:'VOLT',names:['Sparki','Voltfox','Stormane'],color:'#e6b9fb',ability:'Quick recovery',description:'Longer protection after taking a hit.',xp:[120,350]},
 {name:'Coral Drift',label:'BEYOND THE SHALLOWS',intro:'Ride the<br>deep blue.',copy:'Hidden currents. Uncharted wonders.<br>A whole new world below.',icon:'≈',cost:180,colors:['#6ab4bc','#226172','#123847','#98c5bd'],element:'TIDE',names:['Finlet','Reefwing','Tidalune'],color:'#84dce2',ability:'Deep reserves',description:'Start each run with extra health.',xp:[120,350]}
];
export function freshSave(){return {energy:0,best:0,world:0,active:0,unlocked:[true,false,false],creatures:worlds.map(()=>({xp:0,stage:0})),upgrades:{magnet:0,vitality:0}};}
export function restoreSave(raw){const s=freshSave();try{const p=JSON.parse(raw);if(!p||typeof p!=='object')return s;for(const k of ['energy','best'])if(Number.isFinite(p[k])&&p[k]>=0)s[k]=Math.floor(p[k]);for(let i=1;i<3;i++)s.unlocked[i]=p.unlocked?.[i]===true;for(const k of ['active','world'])if(Number.isInteger(p[k])&&p[k]>=0&&p[k]<3&&s.unlocked[p[k]])s[k]=p[k];s.creatures=s.creatures.map((c,i)=>({xp:Number.isFinite(p.creatures?.[i]?.xp)?Math.max(0,Math.floor(p.creatures[i].xp)):0,stage:Math.min(2,Math.max(0,Math.floor(Number(p.creatures?.[i]?.stage)||0)))}));for(const k of ['magnet','vitality'])s.upgrades[k]=Math.min(3,Math.max(0,Math.floor(Number(p.upgrades?.[k])||0)));}catch{}return s;}
export function unlock(s,i){if(!worlds[i]||s.unlocked[i]||s.energy<worlds[i].cost)return false;s.energy-=worlds[i].cost;s.unlocked[i]=true;return true;}
export function evolve(s,i){const c=s.creatures[i];if(!c||c.stage>=2||c.xp<worlds[i].xp[c.stage])return false;c.stage++;return true;}
export function upgradeCost(s,key){return 40*(s.upgrades[key]+1);}
export function upgrade(s,key){if(!Object.hasOwn(s.upgrades,key)||s.upgrades[key]>=3||s.energy<upgradeCost(s,key))return false;s.energy-=upgradeCost(s,key);s.upgrades[key]++;return true;}
export function reward(s,active,distance,energy){const xp=Math.max(1,Math.floor(distance/5));s.energy+=energy;s.best=Math.max(s.best,Math.floor(distance));s.creatures[active].xp+=xp;return xp;}
export function hitsObstacle(type,jump,slide){return type==='rock'?jump<.25:type==='gate'?slide<=0:true;}
