const assetPaths={forest:'assets/forest.webp',neon:'assets/neon.webp',ocean:'assets/ocean.webp',creatures:'assets/creatures.webp',runners:'assets/runners.webp',props:'assets/props.webp'};
export async function loadAssets(onProgress=()=>{}){let loaded=0;const assets={};await Promise.all(Object.entries(assetPaths).map(([key,src])=>new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{assets[key]=image;onProgress(++loaded/Object.keys(assetPaths).length);resolve();};image.onerror=()=>reject(new Error('Artwork could not load. Check your connection and try again.'));image.src=src;})));return assets;}
const worldKeys=['forest','neon','ocean'];
export class GameRenderer{
 constructor(canvas,assets){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.assets=assets;this.particles=[];this.shake=0;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.regions=this.spriteRegions(assets.runners);this.frontRegions=this.spriteRegions(assets.creatures);this.propRegions=this.spriteRegions(assets.props);this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(canvas);this.resize();}
 resize(){const rect=this.canvas.getBoundingClientRect();if(!rect.width||!rect.height)return;this.w=rect.width;this.h=rect.height;const ratio=Math.min(devicePixelRatio||1,2);this.canvas.width=Math.round(this.w*ratio);this.canvas.height=Math.round(this.h*ratio);this.ctx.setTransform(ratio,0,0,ratio,0,0);}
 spriteRegions(image){const c=document.createElement('canvas');c.width=image.width;c.height=image.height;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(image,0,0);const data=x.getImageData(0,0,c.width,c.height).data,cell=image.width/3,regions=[];for(let row=0;row<3;row++){regions[row]=[];for(let col=0;col<3;col++){let minX=cell,minY=cell,maxX=0,maxY=0;for(let y=0;y<cell;y++)for(let xx=0;xx<cell;xx++)if(data[((row*cell+y)*c.width+col*cell+xx)*4+3]>30){minX=Math.min(minX,xx);maxX=Math.max(maxX,xx);minY=Math.min(minY,y);maxY=Math.max(maxY,y);}regions[row][col]={x:col*cell+minX,y:row*cell+minY,w:maxX-minX+1,h:maxY-minY+1};}}return regions;}
 project(lane,z){const p=1-z,s=.065+.935*p*p;return {x:this.w/2+(lane-1)*this.w*.31*s,y:this.h*.50+this.h*.50*p*p,s};}
 polygon(points,fill,stroke){const c=this.ctx;c.beginPath();points.forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.closePath();if(fill){c.fillStyle=fill;c.fill();}if(stroke){c.strokeStyle=stroke;c.lineWidth=1;c.stroke();}}
 ellipse(x,y,rx,ry,color){const c=this.ctx;c.fillStyle=color;c.beginPath();c.ellipse(x,y,Math.max(0,rx),Math.max(0,ry),0,0,Math.PI*2);c.fill();}
 cover(image){const scale=Math.max(this.w/image.width,this.h/image.height);this.ctx.drawImage(image,(this.w-image.width*scale)/2,(this.h-image.height*scale)/2,image.width*scale,image.height*scale);}
 emit(event){if(this.reduced)return;if(event.type==='hit'){this.shake=.28;return;}const p=this.project(event.lane,.1);for(let i=0;i<8;i++)this.particles.push({x:p.x,y:p.y-20,vx:(Math.random()-.5)*150,vy:-50-Math.random()*130,life:.5,max:.5,color:i%2?'#efffb0':'#f4d885'});}
 draw(run,time,dt=0,animate=true){if(!this.w||!run)return;const c=this.ctx,w=this.w,h=this.h,world=run.world,art=this.assets[worldKeys[world]],t=run.time;c.save();if(this.shake>0&&!this.reduced){c.translate(Math.sin(time*70)*this.shake*12,0);this.shake=Math.max(0,this.shake-dt);}this.cover(art);const haze=c.createLinearGradient(0,h*.35,0,h);haze.addColorStop(0,'#071c1520');haze.addColorStop(.5,'#07251b10');haze.addColorStop(1,'#04171150');c.fillStyle=haze;c.fillRect(0,0,w,h);
 // Thin perspective slices turn a real stone texture into a scrolling three-lane road.
 const horizon=h*.50,sections=100;for(let i=0;i<sections;i++){const z1=1-i/sections,z2=1-(i+1)/sections,p1=this.project(1,z1),p2=this.project(1,z2);const width1=w*.51*p1.s,width2=w*.51*p2.s;const sourceY=art.height*(.73+((i/sections*2.5+run.distance*.008)%1)*.20);c.save();this.polygon([[w/2-width1,p1.y],[w/2+width1,p1.y],[w/2+width2,p2.y],[w/2-width2,p2.y]],null);c.clip();c.drawImage(art,art.width*.39,sourceY,art.width*.22,Math.max(1,art.height*.004),w/2-width2,p1.y,width2*2,p2.y-p1.y+1);c.fillStyle=['#3b63392b','#191e483d','#35878a20'][world];c.fillRect(w/2-width2,p1.y,width2*2,p2.y-p1.y+1);c.restore();}
 const fade=c.createLinearGradient(0,horizon,0,horizon+50);fade.addColorStop(0,['#66815f99','#47436d99','#82c3c6aa'][world]);fade.addColorStop(1,'#00000000');c.fillStyle=fade;c.fillRect(w*.44,horizon,w*.12,50);
 for(const lane of [.5,1.5]){c.beginPath();const a=this.project(lane,1),b=this.project(lane,-.02);c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.strokeStyle=world===1?'#d6a1ff55':'#f1e9c638';c.lineWidth=1.5;c.stroke();}
 for(let j=0;j<12;j++){const z=1-((j/12+run.distance*.0016)%1),p=this.project(1,z);c.beginPath();c.moveTo(p.x-w*.50*p.s,p.y);c.lineTo(p.x+w*.50*p.s,p.y);c.strokeStyle='#18332830';c.lineWidth=2*p.s;c.stroke();}
 const drawables=[];for(let j=0;j<14;j++){const z=1-((Math.floor(j/2)/7+run.distance*.0011)%1);drawables.push({z,scenery:true,side:j%2?-1:1,index:j});}for(const o of run.objects)if(o.z<=1&&!o.done)drawables.push(o);drawables.sort((a,b)=>b.z-a.z);for(const item of drawables){if(item.scenery)this.scenery(item,world);else this.object(item,t,world);}
 const p=this.project(run.x,.1),jump=run.jump>0?Math.sin(run.jump/.95*Math.PI)*h*.14:0;this.ellipse(p.x,p.y+2,32*(1-jump/h),8,'#09271e50');if(!run.invincible||Math.floor(run.time*14)%2){const region=this.regions[run.active][run.stage],height=Math.min(w*.28,120)+run.stage*11,width=height*region.w/region.h,bob=animate&&run.jump<=0&&run.slide<=0?Math.abs(Math.sin(run.time*12))*5:0;c.save();c.translate(p.x,p.y-jump-bob);c.rotate(this.reduced?0:(run.lane-run.x)*-.14);if(run.slide>0)c.scale(1.1,.56);c.shadowColor='#042c2170';c.shadowBlur=12;c.drawImage(this.assets.runners,region.x,region.y,region.w,region.h,-width/2,-height,width,height);c.restore();}
 for(let j=0;j<20;j++){const x=(j*127.3+Math.sin(t*.7+j)*10)%w,y=(j*193.8-(this.reduced?0:t*9))%h;this.ellipse(x,y<0?y+h:y,world===2?1.8:1,world===2?1.8:1,world===1?'#e8b3ff5c':'#f3ffd459');}
 if(animate){for(const particle of this.particles){particle.life-=dt;particle.x+=particle.vx*dt;particle.y+=particle.vy*dt;particle.vy+=130*dt;c.globalAlpha=Math.max(0,particle.life/particle.max);this.ellipse(particle.x,particle.y,2.7,2.7,particle.color);}this.particles=this.particles.filter(particle=>particle.life>0);}c.globalAlpha=1;c.restore();}
 scenery(o,world){const p=this.project(1,o.z),x=this.w/2+o.side*this.w*.59*p.s,region=this.propRegions[world][2],height=(world===1?175:126)*p.s,width=height*region.w/region.h;this.ctx.drawImage(this.assets.props,region.x,region.y,region.w,region.h,x-width/2,p.y-height,width,height);}
 object(o,t,world){const c=this.ctx,p=this.project(o.lane,o.z),s=p.s;c.save();c.translate(p.x,p.y);c.scale(s,s);if(o.type==='crystal'){c.translate(0,-28+(this.reduced?0:Math.sin(t*4+o.id)*3));c.rotate(this.reduced?0:Math.sin(t*2+o.id)*.1);c.shadowColor='#e4ffad';c.shadowBlur=15;this.polygon([[0,-19],[13,0],[0,20],[-13,0]],'#d5f77e');c.shadowBlur=0;this.polygon([[0,-19],[0,20],[-13,0]],'#f2ffca');this.polygon([[0,-19],[7,0],[0,9],[-5,0]],'#ffffffb0');}else{const region=this.propRegions[world][o.type==='rock'?0:1],width=o.type==='rock'?90:114,height=o.type==='rock'?65:120;this.ellipse(0,0,width*.44,8,'#102b2933');c.drawImage(this.assets.props,region.x,region.y,region.w,region.h,-width/2,-height,width,height);}c.restore();}
}
