import test from 'node:test';
import assert from 'node:assert/strict';
import {freshSave,restoreSave,unlock,evolve,upgrade,reward,hitsObstacle} from '../model.js';
test('new players start with forest companion; unlocks charge once',()=>{const s=freshSave();assert.equal(unlock(s,1),false);s.energy=280;assert.equal(unlock(s,1),true);assert.equal(unlock(s,1),false);assert.equal(unlock(s,2),true);assert.equal(s.energy,0);assert.deepEqual(s.unlocked,[true,true,true]);});
test('bond gates both evolutions and caps the final form',()=>{const s=freshSave();assert.equal(evolve(s,0),false);s.creatures[0].xp=120;assert.equal(evolve(s,0),true);assert.equal(evolve(s,0),false);s.creatures[0].xp=350;assert.equal(evolve(s,0),true);assert.equal(evolve(s,0),false);});
test('upgrades have increasing costs, affordability checks and a cap',()=>{const s=freshSave();assert.equal(upgrade(s,'vitality'),false);s.energy=300;for(let i=0;i<3;i++)assert.equal(upgrade(s,'vitality'),true);assert.equal(s.energy,60);assert.equal(upgrade(s,'vitality'),false);assert.equal(upgrade(s,'unknown'),false);});
test('run rewards accrue only to active creature and retain the best run',()=>{const s=freshSave();reward(s,0,600,20);reward(s,1,250,12);assert.equal(s.best,600);assert.equal(s.energy,32);assert.equal(s.creatures[0].xp,120);assert.equal(s.creatures[1].xp,50);assert.deepEqual(restoreSave(JSON.stringify(s)),s);});
test('corrupt or unavailable saves recover',()=>{assert.deepEqual(restoreSave('{oops'),freshSave());assert.deepEqual(restoreSave(null),freshSave());const s=restoreSave('{"energy":-20,"world":2,"creatures":[{"stage":100}],"upgrades":{"magnet":-3}}');assert.equal(s.energy,0);assert.equal(s.world,0);assert.equal(s.creatures[0].stage,2);assert.equal(s.upgrades.magnet,0);});
test('rocks require jumps and overhead gates require slides',()=>{assert.equal(hitsObstacle('rock',0,0),true);assert.equal(hitsObstacle('rock',.5,0),false);assert.equal(hitsObstacle('gate',.5,0),true);assert.equal(hitsObstacle('gate',0,.5),false);});
